In [1]:
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import teamgamelog, boxscoreadvancedv2, leaguedashplayerstats, playercareerstats, playergamelog, commonplayerinfo, playerdashboardbygeneralsplits,leaguegamelog, leaguedashteamstats,teamdashboardbygeneralsplits
from nba_api.stats.static import players,teams
from fetch_player_data import *
from fetch_team_data import *
from features import *

## Gather Data and explore it

In [2]:
# import os
# import pandas as pd

# # Load and process data for 2020
# csv_file_path = os.path.join('..','..','Data', 'csv_file', '2020', 'players_clean_df_2020.csv')
# player_data_2020 = pd.read_csv(csv_file_path)

# # Load and process data for 2021
# csv_file_path = os.path.join('..', '..','Data', 'csv_file', '2021', 'players_clean_df_2021.csv')
# player_data_2021 = pd.read_csv(csv_file_path)

# # Load and process data for 2022
# csv_file_path = os.path.join('..','..', 'Data', 'csv_file', '2022', 'players_clean_df_2022.csv')
# player_data_2022 = pd.read_csv(csv_file_path)

# # Load and process data for 2023
# csv_file_path = os.path.join('..','..', 'Data', 'csv_file', '2023', 'players_clean_df_2023.csv')
# player_data_2023 = pd.read_csv(csv_file_path)

# # Load and process data for 2024
# csv_file_path = os.path.join('..','..', 'Data', 'csv_file', '2024', 'players_clean_df_2024.csv')
# player_data_2024 = pd.read_csv(csv_file_path)

# # Concatenate all seasons' data
# seasons_concat = pd.concat([player_data_2020, player_data_2021, player_data_2022, player_data_2023,player_data_2024], ignore_index=True)

In [3]:
csv_file_path = os.path.join('..','..','Data', 'csv_file', 'combined_data', 'combined_clean_df_.csv')
player_data = pd.read_csv(csv_file_path)
player_data.tail()

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM,TEAM_ID,OPPONENT,GAME_ID,GAME_DATE,WL,MIN,...,OPP_REB,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_PACE,GAME_PACE,OPP_PACE,PER,HOME_GAME,USG_PCT_LAST_5,USG_DRTG_INTERACTION
97376,Nathan Knight,1630233,MIN vs. NOP,MIN,1610612750,NOP,22201225,2023-04-09,W,2.0,...,49.0,1.610613e+09,107.989297,104.64,105.70,106.76,4.231500,1,0.2660,53.994648
97377,Lindy Waters III,1630322,OKC vs. MEM,OKC,1610612760,MEM,22201226,2023-04-09,W,12.0,...,43.0,1.610613e+09,111.607143,103.04,101.98,100.92,31.917250,1,0.1502,19.084821
97378,Aaron Wiggins,1630598,OKC vs. MEM,OKC,1610612760,MEM,22201226,2023-04-09,W,8.0,...,43.0,1.610613e+09,111.607143,103.04,101.98,100.92,39.867000,1,0.1614,26.562500
97379,David Roddy,1631223,MEM @ OKC,MEM,1610612763,OKC,22201226,2023-04-09,L,43.0,...,49.0,1.610613e+09,99.088387,100.92,101.98,103.04,20.806512,0,0.1472,21.006738
97380,Onyeka Okongwu,1630168,ATL @ BOS,ATL,1610612737,BOS,22201216,2023-04-09,L,26.0,...,47.0,1.610613e+09,115.900773,98.36,98.26,98.16,34.926192,0,0.1772,16.805612

In [7]:

player_data = add_AST_features(player_data)
player_data.tail()
save_player_stats_to_csv(player_data)

Data saved to /Applications/Documents/PredictorProject/HoopsVista/PropPredictorAI/Data/csv_file/2025/team_df_2025.csv

'/Applications/Documents/PredictorProject/HoopsVista/PropPredictorAI/Data/csv_file/2025/team_df_2025.csv'

In [27]:
player_data.head()

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM,TEAM_ID,OPPONENT,GAME_ID,GAME_DATE,WL,MIN,...,PER,HOME_GAME,USG_PCT_LAST_5,USG_DRTG_INTERACTION,USG_PCT_LAST_3,BLK_LAST_3,BLK_LAST_5,BLK_LAST_7,PLAYER_HOME_AVG_BLK,PLAYER_AWAY_AVG_BLK
292,Vince Carter,1713,ATL @ DET,ATL,1610612737,DET,21900014,2019-10-24,W,10.0,...,-0.258800,0,0.143000,16.690942,0.143000,0.0,0.0,0.0,NaN,0.0
750,Vince Carter,1713,ATL vs. ORL,ATL,1610612737,ORL,21900028,2019-10-26,W,12.0,...,21.072000,1,0.129000,11.892570,0.129000,0.0,0.0,0.0,0.0,0.0
958,Vince Carter,1713,ATL vs. PHI,ATL,1610612737,PHI,21900043,2019-10-28,L,11.0,...,34.360364,1,0.155333,19.287000,0.155333,0.0,0.0,0.0,0.0,0.0
1115,Vince Carter,1713,ATL @ MIA,ATL,1610612737,MIA,21900052,2019-10-29,L,18.0,...,17.300667,0,0.167750,19.017789,0.176000,0.0,0.0,0.0,0.0,0.0
1434,Vince Carter,1713,ATL vs. MIA,ATL,1610612737,MIA,21900066,2019-10-31,L,16.0,...,6.563062,1,0.158600,11.900644,0.178333,0.0,0.0,0.0,0.0,0.0